# This workflow will build a Elephant project
# For more information see: https://qualitycoding.org/github-actions-ci-xcode/

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild  -v
    - name: Run tests
      run: xcodebuild  -v
