# This workflow will build a Elephant project
# For more information see: https://qualitycoding.org/github-actions-ci-xcode/

name: Elephant CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests on iOS
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild  -v
    - name: Run tests
      run: xcodebuild  -v
